#!/bin/bash

#SBATCH --partition=p_ccib_1                    # which partition to run the job, options are in the Amarel guide
#SBATCH --exclude=gpuc001,gpuc002               # exclude CCIB GPUs
#SBATCH --account=general
#SBATCH --job-name=bwa                          # job name for listing in queue
#SBATCH --output=/projects/f_geneva_1/alyssa/grahami/pilon/150/slurm-%j-%x.out
#SBATCH --mem=100G                              # memory to allocate in Mb
#SBATCH -n 10                                   # number of cores to use
#SBATCH -N 1                                    # number of nodes the cores should be on, 1 means all cores on same node
#SBATCH --time=3-00:00:00                       # maximum run time days-hours:minutes:seconds
#SBATCH --requeue                               # restart and paused or superseeded jobs
#SBATCH --mail-user=av795@rutgers.edu           # email address to send status updates
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE      # email for the following reasons



echo "load any Amarel modules that script requires"
module purge                                    # clears out any pre-existing modules
module load samtools                            # load any modules needed
module load bwa

echo "Bash commands for the analysis you are going to run"

echo "##################### index and align with BWA"
bwa index /projects/f_geneva_1/alyssa/grahami/sealer/run2_scaffold.fa

bwa mem -t 10 /projects/f_geneva_1/alyssa/grahami/sealer/run2_scaffold.fa \
/projects/f_geneva_1/alyssa/grahami/DTG-SG-150_filtered.R1.fq \
/projects/f_geneva_1/alyssa/grahami/DTG-SG-150_filtered.R2.fq \
| samtools sort -@10 -o /projects/f_geneva_1/alyssa/grahami/pilon/150/150_bwa_aligned.bam -


echo "change user group of files created"
chgrp -R g_geneva_1 /projects/f_geneva_1/alyssa/grahami/pilon/150             # changes group of all files in listed directory


echo "This is a run"
echo "Now it is done"
