#!/bin/bash

#SBATCH --partition=p_ccib_1                    # which partition to run the job, options are in the Amarel guide
#SBATCH --exclude=gpuc001,gpuc002               # exclude CCIB GPUs
#SBATCH --account=general
#SBATCH --job-name=fastqc                       # job name for listing in queue
#SBATCH --output=/projects/f_geneva_1/alyssa/grahami/fastqc/slurm-%j-%x.out
#SBATCH --mem=100G                              # memory to allocate in Mb
#SBATCH -n 20                                   # number of cores to use
#SBATCH -N 1                                    # number of nodes the cores should be on, 1 means all cores on same node
#SBATCH --time=3-00:00:00                       # maximum run time days-hours:minutes:seconds
#SBATCH --requeue                               # restart and paused or superseeded jobs
#SBATCH --mail-user=av795@rutgers.edu           # email address to send status updates
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE      # email for the following reasons


echo "load any Amarel modules that script requires"
module purge                                    # clears out any pre-existing modules
module load java                                # load any modules needed
module load FastQC

echo "Bash commands for the analysis you are going to run"

readset="/projects/f_geneva_1/alyssa/grahami/DTG-SG-149"

echo "##################### fastqc initial quality analysis"
fastqc -t 20 \
${readset}_R1_001.fastq \
${readset}_R2_001.fastq \
-o /projects/f_geneva_1/alyssa/grahami/fastqc

echo ""
echo "##################### trimmomatic"
java -jar /projects/ccib/geneva/programs/trimmomatic/trimmomatic-0.39.jar PE \
-threads 20 -phred33 -trimlog ${readset}_trim.log \
${readset}_R1_001.fastq ${readset}_R2_001.fastq \
${readset}_filtered.R1.fq ${readset}_filtered.unpaired.R1.fq \
${readset}_filtered.R2.fq ${readset}_filtered.unpaired.R2.fq \
ILLUMINACLIP:/projects/ccib/geneva/programs/trimmomatic/adapters/TruSeq3-PE-2.fa:2:30:10:4 \
LEADING:20 TRAILING:20 SLIDINGWINDOW:13:20 MINLEN:23

echo ""
echo "##################### fastqc trimmomatic quality analysis"
fastqc -t 20 \
${readset}_filtered.R1.fq \
${readset}_filtered.R2.fq \
-o /projects/f_geneva_1/alyssa/grahami/fastqc
