#!/bin/bash

#SBATCH --partition=p_ccib_1                    # which partition to run the job, options are in the Amarel guide
#SBATCH --exclude=gpuc001,gpuc002               # exclude CCIB GPUs
#SBATCH --account=general
#SBATCH --job-name=stats                        # job name for listing in queue
#SBATCH --output=/projects/f_geneva_1/alyssa/grahami/stats/slurm-%j-%x.out
#SBATCH --mem=10G                               # memory to allocate in Mb
#SBATCH -n 10                                   # number of cores to use
#SBATCH -N 1                                    # number of nodes the cores should be on, 1 means all cores on same node
#SBATCH --time=10:00:00                         # maximum run time days-hours:minutes:seconds
#SBATCH --requeue                               # restart and paused or superseeded jobs
#SBATCH --mail-user=av795@rutgers.edu           # email address to send status updates
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE      # email for the following reasons


echo "load any Amarel modules that script requires"
module purge                                    # clears out any pre-existing modules
module load java                                # load any modules needed


echo "Bash commands for the analysis you are going to run"
#stats.sh in=run3_scaffold.fa
#stats.sh in=anolis_cristatellu_09Oct2018_QyJEk.fasta
#stats.sh in=Asm2m66700.scaffolds.fa
#stats.sh in=/projects/f_geneva_1/alyssa/grahami/sealer/run1_scaffold.fa
stats.sh in=/projects/f_geneva_1/alyssa/grahami/sealer/run2_scaffold.fa


echo "change user group of files created"
chgrp -R g_geneva_1 /projects/f_geneva_1/alyssa/grahami/stats         # changes group of all files in listed directory


echo "This is a run"
echo "Now it is done"
